### ISSUE TITLE
HomeMultipleRecycleAdapter缺少方法setFilling

### ISSUE THREAD

**Issue by Karuao** [liu-xiao-dong/JD-Test#1]
编译后出现错误
![image](https://cloud.githubusercontent.com/assets/27544584/25070766/06d16d34-22da-11e7-8891-790e718c2631.png)
![image](https://cloud.githubusercontent.com/assets/27544584/25070793/461529cc-22da-11e7-8732-1dd04f12dac2.png)

**Comment by liu-xiao-dong** [comment]
此方法已经废弃，我会更新一下代码，谢谢指出问题！
