### ISSUE TITLE
老哥，期待你的更新

### ISSUE THREAD

**Issue by Xmaoyh** [liu-xiao-dong/JD-Test#10]

**Comment by liu-xiao-dong** [comment]
最近工作比较忙，另一方面是也想不到要增加什么功能可以帮助大家更快开发，或着说给大家带来更多进步，所以一直也没更新，你也可以对你期待新增的功能给我留言，如果对大家开发有益处，我会抽空加上，欢迎留建议。

**Comment by Xmaoyh** [comment]
很期待对商品详情页的简单实现

**Comment by liu-xiao-dong** [comment]
可以，我有空加上！

**Comment by Xmaoyh** [comment]
赞！

**Comment by liu-xiao-dong** [comment]
https://github.com/Hankkin/TaoBaoDetailDemo  不错的解决方案，暂时没时间做，你可以参考
