### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by xuyunqiang** [liu-xiao-dong/JD-Test#13]
对于DataManager这个东西放在Common库里面，太儿戏了，所有模块的model层都将下层到Common库中，这样子怕是很难后面独立开发，以及模块越多Common会爆炸的，我现在遇到的问题也是用Dagger2实现依赖注入，也有类似DataManager这类，也必须声明成@Singleton，然而ApplicationComponent也放在Common库中，但是我想在各个模块定义自己的DataManager实现真正的model水平化解耦，但是这样子就不能声明成@Singleton了，这如何是好

**Comment by liu-xiao-dong** [comment]
在项目的使用中我也发现这个问题，我的解决办法是在每个模块中建立本模块的DataManager，使用装饰模式持有Common模块中的DataManager,进行本模块功能扩展，如果你有更好的解决办法可以相互交流下。

**Comment by liu-xiao-dong** [comment]
在项目的使用中我也发现这个问题，我的解决办法是在每个模块中建立本模块的DataManager，使用装饰模式持有Common模块中的DataManager,进行本模块功能扩展，如果你有更好的解决办法可以相互交流下。

**Comment by liu-xiao-dong** [comment]
详细见项目
