### ISSUE TITLE
写的好棒(*^▽^*)

### ISSUE THREAD

**Issue by OhPeterPan** [liu-xiao-dong/JD-Test#14]
里面就一个刷新已经看迷了，希望出配套的讲解文档，在文末也可以给个支付宝微信二维码啥的，支持一波ヾ(◍°∇°◍)ﾉﾞ

**Comment by liu-xiao-dong** [comment]
最开始有打算出详细的文档，后来感觉内部使用并没有太多新的东西，大多功能是由三方库组成，而三方库一般也有较详细的文档，所以本人只在组件化及整体架构写了相关文档。关于打赏，本人在此开源项目上的投入还是不太够，自然也不好意思求赏。
