### ISSUE TITLE
可以按照当前京东App版本实现Statusbar颜色与banner图片背景一致吗

### ISSUE THREAD

**Issue by CrossYourSoul** [liu-xiao-dong/JD-Test#16]
可以按照当前京东App版本实现Statusbar颜色与banner图片背景一致吗

**Comment by liu-xiao-dong** [comment]
我查看8.1/6.1最新版本并没有此功能，如果想做我提供的思路是：使用沉浸式状态栏，用view去占位状态栏背景，根据提取banner主颜色去改变背景view颜色
