### ISSUE TITLE
JD-Test/common/src/main/java/com/sxjs/common/base/baseadapter

### ISSUE THREAD

**Issue by ghost** [liu-xiao-dong/JD-Test#2]
JD-Test/common/src/main/java/com/sxjs/common/base/baseadapter，这个其实可以用gradle直接用的，不用做为library，而且还在不停的更新中

**Comment by liu-xiao-dong** [comment]
因为我在BaseQuickAdapter中的convert方法加了一个position的参数，所以只有将代码copy到项目中更改了，这个看需求，如果开源框架够用就直接Gradle引入就可以！
