### ISSUE TITLE
我用新版本的androidstudio 3.3.1版本，好像gradle版本和butterknife版本有问题了

### ISSUE THREAD

**Issue by durandal1981** [liu-xiao-dong/JD-Test#20]
我用新版本的androidstudio 3.3.1版本，好像gradle版本和butterknife版本有问题了

**Comment by zlrambo** [comment]
将butterknife版本改为：9.0.0-SNAPSHOT，同时在allprojects的repositories 和 buildscript的repositories节点下增加maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
