### ISSUE TITLE
关于组件化

### ISSUE THREAD

**Issue by whyalwaysmea** [liu-xiao-dong/JD-Test#5]
现在的组件化只是搭建了架构而已吗？ 会有下一步跟进吗？
还是说首页完成这个项目也就差不多了？组件化只是test而已？

**Comment by liu-xiao-dong** [comment]
这个组件化的架构基本成型，如果是在项目中应用，业务module当然更丰富一些，接下来有时间我会增加通讯组件、地图组件等常用的组件，UI也会选一些京东app上比较有难度的页面，内部结构也会做不断的优化，当然，只能在工作之余做这些！
