### ISSUE TITLE
ButterKnife  完全在BaseActivity中初始化

### ISSUE THREAD

**Issue by tsm19911014** [liu-xiao-dong/JD-Test#8]
public abstract class BaseActivity extends AppCompatActivity {

    private Unbinder bindler;

    protected abstract int getLayoutID();

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(this.getLayoutID());/////利用抽象方法获得layoutid,就可以在父类中初始化了,
        bindler=ButterKnife.bind(this);////绑定前要确认布局已经被添加,否则会报错
        LogUtils.i("------------" + this.getClass().getSimpleName() + "--------------");
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        InputUtil.hideKeyBoard(this);
        return super.onTouchEvent(event);
    }

    @Override
    protected void onDestroy() {
        if(bindler!=null)
            bindler.unbind();
        super.onDestroy();
    }
}

**Comment by liu-xiao-dong** [comment]
It's a good idea!

**Comment by liu-xiao-dong** [comment]
使用ButterKnife快捷键是会再次在onCreate中生成ButterKnife.bind(this);所以我也就没抽取！而且也很享受覆写onCreate的过程，大家如果喜欢可以按以上的方法抽取到基类使用！
