### ISSUE TITLE
模块A和模块B都依赖CommonLibrary,会让包体积变大吗

### ISSUE THREAD

**Issue by CK875430315** [liu-xiao-dong/JD-Test#9]
模块A和模块B都依赖CommonLibrary,会让包体积变大吗

**Comment by liu-xiao-dong** [comment]
不会，相当于依赖三方库一样，保持版本号一致就不会重复打包，开启混淆也会剔除无用代码。

**Comment by CK875430315** [comment]
保持版本号，是指CommonLibrary的版本号吗

**Comment by liu-xiao-dong** [comment]
依赖common不会增加，我说的是依赖其它三方库的情况，比如这样：compile 'com.google.android.exoplayer:exoplayer:r2.4.0'，我说的是两种情况

**Comment by CK875430315** [comment]
哦哦 懂了
